---
apiVersion: v1
kind: Service
metadata:
   name: private-repository-k8s
   labels:
     app: private-repository-k8s
spec:
   ports:
   - port: 5000
     protocol: TCP
     targetPort: 5000
   selector:
     app: private-repository-k8s
   type: NodePort
