apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-dev-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
